version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: xcrack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: xcrack
      POSTGRES_PASSWORD: xcrack_password
      POSTGRES_DB: xcrack_liquidation
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xcrack -d xcrack_liquidation"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - xcrack-network

  redis:
    image: redis:7-alpine
    container_name: xcrack-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - xcrack-network

  # pgAdmin (optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: xcrack-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@xcrack.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - xcrack-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  xcrack-network:
    driver: bridge
