# xCrack AI 예측 시스템 설정

data:
  collection_interval: 5  # 초
  symbols:
    - "ETH/USDT"
    - "BTC/USDT"
    - "WETH/USDC"
    - "DAI/USDC"
  exchanges:
    - "binance"
    - "uniswap_v3"
    - "sushiswap"
  mempool_sources:
    - "flashbots"
    - "blocknative"
    - "eden"
  historical_days: 30

analysis:
  technical_indicators:
    - "rsi"
    - "macd"
    - "bollinger_bands"
    - "ema"
    - "volume_profile"
  lookback_periods: [14, 30, 60, 120]
  volatility_window: 20
  correlation_threshold: 0.7

mev:
  min_confidence: 0.8
  min_profit_threshold: 0.01  # 1%
  gas_price_multiplier: 1.2
  block_time_estimate: 12  # 초
  opportunity_types:
    - "sandwich"
    - "arbitrage"
    - "liquidation"
    - "frontrun"

models:
  lstm:
    hidden_size: 128
    num_layers: 2
    dropout: 0.2
    sequence_length: 60
    learning_rate: 0.001
    batch_size: 32
  
  transformer:
    d_model: 128
    nhead: 8
    num_layers: 6
    dropout: 0.1
    learning_rate: 0.0001
    batch_size: 32
  
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    random_state: 42
  
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    random_state: 42
  
  model_save_dir: "saved_models"
  retrain_interval_hours: 24

prediction:
  interval_seconds: 10
  confidence_threshold: 0.7
  max_predictions_per_symbol: 10
  prediction_horizons: [5, 15, 30, 60]  # 분

communication:
  host: "localhost"
  port: 8080
  protocol: "websocket"  # websocket, redis, tcp
  reconnect_interval: 5
  heartbeat_interval: 30
  redis_url: "redis://localhost:6379"
  tcp_keepalive: true

# 로깅 설정
logging:
  level: "INFO"
  file: "logs/ai_predictor.log"
  max_file_size: "10MB"
  backup_count: 5

# 성능 설정
performance:
  enable_gpu: true
  max_workers: 4
  batch_processing: true
  cache_size: 1000