# xCrack Rust MEV Searcher Configuration

[network]
chain_id = 1
name = "mainnet"
rpc_url = "https://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
ws_url = "wss://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
block_time = 12

[blockchain]
enable_onchain_strategies = true
mempool_monitoring = true
event_listening = true
max_rpc_calls_per_second = 100
cache_ttl_seconds = 60

[blockchain.primary_network]
chain_id = 1
name = "mainnet"
rpc_url = "https://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
ws_url = "wss://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
block_time = 12

[[blockchain.backup_networks]]
chain_id = 1
name = "mainnet-backup"
rpc_url = "https://mainnet.infura.io/v3/YOUR_PROJECT_ID"
ws_url = "wss://mainnet.infura.io/ws/v3/YOUR_PROJECT_ID"
block_time = 12

[strategies]

[strategies.arbitrage]
enabled = true
min_profit_threshold = "0.01"  # Minimum 0.01 ETH profit
max_trade_size = "10.0"        # Maximum 10 ETH trade size
max_price_impact = 0.05        # Maximum 5% price impact
supported_dexes = ["uniswap_v2", "sushiswap", "uniswap_v3"]

[strategies.sandwich]
enabled = true
min_target_value = "0.5"       # Minimum 0.5 ETH victim transaction
max_slippage = 0.03           # Maximum 3% slippage to cause
max_frontrun_size = "5.0"     # Maximum 5 ETH frontrun
min_profit_eth = "0.01"       # Minimum 0.01 ETH profit
min_profit_percentage = 0.02  # Minimum 2% profit
gas_multiplier = 1.2          # 20% gas price increase
max_gas_price_gwei = "100"    # Maximum 100 gwei

[strategies.liquidation]
enabled = true
protocols = ["aave", "compound", "makerdao"]
min_health_factor = 1.05      # Liquidate below 1.05 health factor
max_liquidation_amount = "50.0"  # Maximum 50 ETH liquidation
min_profit_eth = "0.01"       # Minimum 0.01 ETH profit
min_liquidation_amount = "0.1"  # Minimum 0.1 ETH liquidation
gas_multiplier = 1.5          # 50% gas price increase for competitive liquidation
max_gas_price_gwei = "200"    # Maximum 200 gwei for liquidation
health_factor_threshold = 1.0 # Health factor threshold for liquidation
max_liquidation_size = "100.0"  # Maximum 100 ETH liquidation size

[strategies.micro_arbitrage]
enabled = true
trading_pairs = ["WETH/USDC", "WETH/USDT", "WETH/DAI", "WBTC/USDC", "WBTC/USDT"]
min_profit_percentage = 0.001      # 0.1% minimum profit
min_profit_usd = "10.0"           # Minimum $10 profit
max_position_size = "5.0"         # Maximum 5 ETH position
max_concurrent_trades = 3         # Maximum 3 concurrent trades
execution_timeout_ms = 5000       # 5 second timeout
latency_threshold_ms = 100        # 100ms latency threshold
price_update_interval_ms = 50     # 50ms price update interval
order_book_depth = 10             # Top 10 levels
slippage_tolerance = 0.005        # 0.5% slippage tolerance
fee_tolerance = 0.003             # 0.3% fee tolerance
risk_limit_per_trade = "1.0"      # 1 ETH risk per trade
daily_volume_limit = "100.0"      # 100 ETH daily volume limit
enable_cex_trading = true         # Enable CEX trading
enable_dex_trading = true         # Enable DEX trading
blacklist_tokens = []             # No blacklisted tokens
priority_tokens = ["WETH", "USDC", "USDT", "DAI", "WBTC"]  # Priority tokens
runtime_blacklist_ttl_secs = 900  # 15분 TTL

# Exchange configurations for micro arbitrage
[[strategies.micro_arbitrage.exchanges]]
name = "uniswap_v2"
exchange_type = "DEX"
enabled = true
api_endpoint = "https://api.uniswap.org/v1"
trading_pairs = ["WETH/USDC", "WETH/USDT", "WETH/DAI"]
fee_percentage = 0.003            # 0.3% fee
min_order_size = "0.01"          # 0.01 ETH minimum
max_order_size = "10.0"          # 10 ETH maximum
rate_limit_per_second = 10       # 10 requests per second
supports_fast_execution = true

[[strategies.micro_arbitrage.exchanges]]
name = "sushiswap"
exchange_type = "DEX"
enabled = true
api_endpoint = "https://api.sushi.com/v1"
trading_pairs = ["WETH/USDC", "WETH/USDT", "WETH/DAI"]
fee_percentage = 0.003            # 0.3% fee
min_order_size = "0.01"          # 0.01 ETH minimum
max_order_size = "10.0"          # 10 ETH maximum
rate_limit_per_second = 10       # 10 requests per second
supports_fast_execution = true

[[strategies.micro_arbitrage.exchanges]]
name = "mock_binance"
exchange_type = "CEX"
enabled = true
api_endpoint = "https://api.binance.com/api/v3"
trading_pairs = ["WETH/USDC", "WETH/USDT", "WBTC/USDC"]
fee_percentage = 0.001            # 0.1% fee
min_order_size = "0.001"         # 0.001 ETH minimum
max_order_size = "50.0"          # 50 ETH maximum
rate_limit_per_second = 20       # 20 requests per second
websocket_endpoint = "wss://stream.binance.com:9443/ws"
supports_fast_execution = true

[[strategies.micro_arbitrage.exchanges]]
name = "mock_coinbase"
exchange_type = "CEX"
enabled = true
api_endpoint = "https://api.exchange.coinbase.com"
trading_pairs = ["WETH/USDC", "WETH/DAI", "WBTC/USDC"]
fee_percentage = 0.0025           # 0.25% fee
min_order_size = "0.001"         # 0.001 ETH minimum
max_order_size = "25.0"          # 25 ETH maximum
rate_limit_per_second = 10       # 10 requests per second
websocket_endpoint = "wss://ws-feed.exchange.coinbase.com"
supports_fast_execution = true

[flashbots]
network = "mainnet"                    # Network for Flashbots (mainnet, goerli, sepolia)
relay_url = "https://relay.flashbots.net"
builder_urls = [
    "https://relay.flashbots.net",
    "https://builder0x69.io",
    "https://rpc.beaverbuild.org"
]
max_priority_fee_per_gas = "2"  # 2 gwei
max_fee_per_gas = "50"          # 50 gwei
private_key = "0x0000000000000000000000000000000000000000000000000000000000000001"

# Bridge Configuration for Cross-chain Arbitrage
[bridges]
enabled = true
default_slippage = 0.5              # 0.5% default slippage
max_bridge_time = 1800              # 30 minutes maximum bridge time
preferred_bridges = ["lifi", "stargate", "hop"]  # Preferred bridges in order
lifi_api_key = ""                   # Optional LI.FI API key for higher rate limits
enable_aggregation = true           # Use LI.FI for bridge aggregation

[safety]
max_concurrent_bundles = 5
max_daily_gas_spend = "1.0"     # 1 ETH per day
emergency_stop_loss = "0.1"     # Stop if lose 0.1 ETH
max_position_size = "10.0"      # Maximum 10 ETH position
enable_emergency_stop = true

[monitoring]
enable_discord_alerts = false
discord_webhook_url = ""
enable_telegram_alerts = false
telegram_bot_token = ""
telegram_chat_id = ""
profit_report_interval = "0 8 * * *"  # Daily at 8 AM
log_level = "info"
metrics_port = 9090

[performance]
max_concurrent_analysis = 10
batch_processing_interval = 100  # milliseconds
mempool_filter_min_value = "0.1"     # 0.1 ETH minimum
mempool_filter_min_gas_price = "10"  # 10 gwei minimum
mempool_filter_max_gas_price = "500" # 500 gwei maximum
enable_metrics = true
cache_size = 10000

# DEX Configurations
[[dexes]]
name = "uniswap_v2"
router = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
factory = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
fee = 300  # 0.3%
enabled = true

[[dexes]]
name = "sushiswap"
router = "0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F"
factory = "0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac"
fee = 300  # 0.3%
enabled = true

[[dexes]]
name = "uniswap_v3"
router = "0xE592427A0AEce92De3Edee1F18E0157C05861564"
factory = "0x1F98431c8aD98523631AE4a59f267346ea31F984"
fee = 500  # Variable fees
enabled = true

# Token Addresses
[tokens]
WETH = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
USDC = "0xA0b86a33E6417f8C681A1fFE6954e127c9cd8e46"
USDT = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
DAI = "0x6B175474E89094C44Da98b954EedeAC495271d0F"
WBTC = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"