# xCrack Rust MEV Searcher Configuration

[network]
chain_id = 1
name = "mainnet"
rpc_url = "https://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
ws_url = "wss://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
block_time = 12

[blockchain]
enable_onchain_strategies = true
mempool_monitoring = true
event_listening = true
max_rpc_calls_per_second = 100
cache_ttl_seconds = 60

[blockchain.primary_network]
chain_id = 1
name = "mainnet"
rpc_url = "https://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
ws_url = "wss://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
block_time = 12
flashloan_receiver = "0x0000000000000000000000000000000000000000" # set your deployed FlashLoanReceiver here
# Optional strategy-specific executors (preferred)
arbitrage_contract = "0x0000000000000000000000000000000000000000" # contracts/Arbitrage.sol deployed address
liquidation_contract = "0x0000000000000000000000000000000000000000" # contracts/Liquidation.sol deployed address
sandwich_contract = "0x0000000000000000000000000000000000000000" # contracts/Sandwich.sol deployed address
# Optional override if you deploy on different network fork (else code uses default Aave V3 pool const)
# aave_v3_pool = "0x87870bca3f3fd633543545f15f8073b8a42ad6f8"

[[blockchain.backup_networks]]
chain_id = 1
name = "mainnet-backup"
rpc_url = "https://mainnet.infura.io/v3/YOUR_PROJECT_ID"
ws_url = "wss://mainnet.infura.io/ws/v3/YOUR_PROJECT_ID"
block_time = 12

[strategies]

[strategies.arbitrage]
enabled = true
min_profit_threshold = "0.01"  # Minimum 0.01 ETH profit
max_trade_size = "10.0"        # Maximum 10 ETH trade size
max_price_impact = 0.05        # Maximum 5% price impact
supported_dexes = ["uniswap_v2", "sushiswap", "uniswap_v3"]

[strategies.sandwich]
enabled = true
min_target_value = "0.5"       # Minimum 0.5 ETH victim transaction
max_slippage = 0.03           # Maximum 3% slippage to cause
max_frontrun_size = "5.0"     # Maximum 5 ETH frontrun
min_profit_eth = "0.01"       # Minimum 0.01 ETH profit
min_profit_percentage = 0.02  # Minimum 2% profit
gas_multiplier = 1.2          # 20% gas price increase
max_gas_price_gwei = "100"    # Maximum 100 gwei
use_flashloan = false          # Use flashloan-assisted sandwich
# flash_loan_amount = "10.0"   # Optional flash loan amount (ETH or token units)

[strategies.liquidation]
enabled = true
protocols = ["aave", "compound", "makerdao"]
min_health_factor = 1.05      # Liquidate below 1.05 health factor
max_liquidation_amount = "50.0"  # Maximum 50 ETH liquidation
min_profit_eth = "0.01"       # Minimum 0.01 ETH profit
min_liquidation_amount = "0.1"  # Minimum 0.1 ETH liquidation
gas_multiplier = 1.5          # 50% gas price increase for competitive liquidation
max_gas_price_gwei = "200"    # Maximum 200 gwei for liquidation
health_factor_threshold = 1.0 # Health factor threshold for liquidation
max_liquidation_size = "100.0"  # Maximum 100 ETH liquidation size

[strategies.micro_arbitrage]
enabled = true
trading_pairs = ["WETH/USDC", "WETH/USDT", "WETH/DAI", "WBTC/USDC", "WBTC/USDT"]
min_profit_percentage = 0.001      # 0.1% minimum profit
min_profit_usd = "10.0"           # Minimum $10 profit
max_position_size = "5.0"         # Maximum 5 ETH position
max_concurrent_trades = 3         # Maximum 3 concurrent trades
execution_timeout_ms = 5000       # 5 second timeout
latency_threshold_ms = 100        # 100ms latency threshold
price_update_interval_ms = 50     # 50ms price update interval
order_book_depth = 10             # Top 10 levels
slippage_tolerance = 0.005        # 0.5% slippage tolerance
fee_tolerance = 0.003             # 0.3% fee tolerance
risk_limit_per_trade = "1.0"      # 1 ETH risk per trade
daily_volume_limit = "100.0"      # 100 ETH daily volume limit
enable_cex_trading = true         # Enable CEX trading
enable_dex_trading = true         # Enable DEX trading
blacklist_tokens = []             # No blacklisted tokens
priority_tokens = ["WETH", "USDC", "USDT", "DAI", "WBTC"]  # Priority tokens
runtime_blacklist_ttl_secs = 900  # 15분 TTL
use_flashloan = false              # Use flashloan to borrow base for DEX arbitrage
# flash_loan_amount = "10000"      # Optional amount (e.g., 10,000 USDC)

# Exchange configurations for micro arbitrage
[[strategies.micro_arbitrage.exchanges]]
name = "uniswap_v2"
exchange_type = "DEX"
enabled = true
api_endpoint = "https://api.uniswap.org/v1"
trading_pairs = ["WETH/USDC", "WETH/USDT", "WETH/DAI"]
fee_percentage = 0.003            # 0.3% fee
min_order_size = "0.01"          # 0.01 ETH minimum
max_order_size = "10.0"          # 10 ETH maximum
rate_limit_per_second = 10       # 10 requests per second
supports_fast_execution = true


[[strategies.micro_arbitrage.exchanges]]
name = "sushiswap"
exchange_type = "DEX"
enabled = true
api_endpoint = "https://api.sushi.com/v1"
trading_pairs = ["WETH/USDC", "WETH/USDT", "WETH/DAI"]
fee_percentage = 0.003            # 0.3% fee
min_order_size = "0.01"          # 0.01 ETH minimum
max_order_size = "10.0"          # 10 ETH maximum
rate_limit_per_second = 10       # 10 requests per second
supports_fast_execution = true

[[strategies.micro_arbitrage.exchanges]]
name = "mock_binance"
exchange_type = "CEX"
enabled = true
api_endpoint = "https://api.binance.com/api/v3"
trading_pairs = ["WETH/USDC", "WETH/USDT", "WBTC/USDC"]
fee_percentage = 0.001            # 0.1% fee
min_order_size = "0.001"         # 0.001 ETH minimum
max_order_size = "50.0"          # 50 ETH maximum
rate_limit_per_second = 20       # 20 requests per second
websocket_endpoint = "wss://stream.binance.com:9443/ws"
supports_fast_execution = true

[[strategies.micro_arbitrage.exchanges]]
name = "mock_coinbase"
exchange_type = "CEX"
enabled = true
api_endpoint = "https://api.exchange.coinbase.com"
trading_pairs = ["WETH/USDC", "WETH/DAI", "WBTC/USDC"]
fee_percentage = 0.0025           # 0.25% fee
min_order_size = "0.001"         # 0.001 ETH minimum
max_order_size = "25.0"          # 25 ETH maximum
rate_limit_per_second = 10       # 10 requests per second
websocket_endpoint = "wss://ws-feed.exchange.coinbase.com"
supports_fast_execution = true

[flashbots]
network = "mainnet"                    # Network for Flashbots (mainnet, goerli, sepolia)
relay_url = "https://relay.flashbots.net"
builder_urls = [
    "https://relay.flashbots.net",
    "https://builder0x69.io",
    "https://rpc.beaverbuild.org"
]
max_priority_fee_per_gas = "2"  # 2 gwei
max_fee_per_gas = "50"          # 50 gwei
private_key = "0x0000000000000000000000000000000000000000000000000000000000000001"


[safety]
max_concurrent_bundles = 5
max_daily_gas_spend = "1.0"     # 1 ETH per day
emergency_stop_loss = "0.1"     # Stop if lose 0.1 ETH
max_position_size = "10.0"      # Maximum 10 ETH position
enable_emergency_stop = true

[monitoring]
enable_discord_alerts = false
discord_webhook_url = ""
enable_telegram_alerts = false
telegram_bot_token = ""
telegram_chat_id = ""
profit_report_interval = "0 8 * * *"  # Daily at 8 AM
log_level = "info"
metrics_port = 9090
api_port = 8080

[performance]
max_concurrent_analysis = 10
batch_processing_interval = 100  # milliseconds
mempool_filter_min_value = "0.1"     # 0.1 ETH minimum
mempool_filter_min_gas_price = "10"  # 10 gwei minimum
mempool_filter_max_gas_price = "500" # 500 gwei maximum
enable_metrics = true
cache_size = 10000

# DEX Configurations
[[dexes]]
name = "uniswap_v2"
router = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
factory = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
fee = 300  # 0.3%
enabled = true

[[dexes]]
name = "sushiswap"
router = "0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F"
factory = "0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac"
fee = 300  # 0.3%
enabled = true

[[dexes]]
name = "uniswap_v3"
router = "0xE592427A0AEce92De3Edee1F18E0157C05861564"
factory = "0x1F98431c8aD98523631AE4a59f267346ea31F984"
fee = 500  # Variable fees
enabled = true

# DEX API Configuration
[dex]
ox_api_key = ""
oneinch_api_key = ""
request_timeout_ms = 5000
retry_count = 3
rate_limit_per_second = 10

# Execution Configuration
[execution]
gas_price_gwei = 20.0
gas_multiplier = 1.2
transaction_timeout_ms = 30000
max_pending_transactions = 10

# Liquidation V2 Configuration
[liquidation]
min_profit_threshold_usd = 50.0
scan_interval_seconds = 30
max_concurrent_liquidations = 5
use_flashloan = false
preferred_flashloan_provider = "aave"

# Protocol Configuration
[protocols]
[protocols.aave]
enabled = true
contract_address = "0x87870Bca3F3fD633543545F15f8073B8A42aD6f8"
oracle_address = "0x54586bE62E3c3580375aE3723C145253060Ca0C2"
liquidation_threshold = 0.8
close_factor = 0.5
liquidation_bonus = 0.05

[protocols.compound_v2]
enabled = true
contract_address = "0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B"
oracle_address = "0x50ce56A3239671Ab62f185704Caedf626352741e"
liquidation_threshold = 0.75
close_factor = 0.5
liquidation_bonus = 0.08

[protocols.compound_v3]
enabled = false
liquidation_threshold = 0.8
close_factor = 0.5
liquidation_bonus = 0.05

[protocols.makerdao]
enabled = true
contract_address = "0x35D1b3F3D7966A1DFe207aa4514C12a259A0492B"
oracle_address = "0x81FE72B5A8d1A857d176C3E7d5Bd2679A9B85763"
liquidation_threshold = 0.75
close_factor = 1.0
liquidation_bonus = 0.13

# Contract Configuration
[contracts]
liquidation_strategy = "0x0000000000000000000000000000000000000000"
flashloan_receiver = "0x0000000000000000000000000000000000000000"
dex_router = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"

# Token Addresses
[tokens]
WETH = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
USDC = "0xA0b86a33E6417f8C681A1fFE6954e127c9cd8e46"
USDT = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
DAI = "0x6B175474E89094C44Da98b954EedeAC495271d0F"
WBTC = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"