# xCrack Rust MEV Searcher Configuration

[network]
chain_id = 1
name = "mainnet"
rpc_url = "https://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
ws_url = "wss://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
block_time = 12

[strategies]

[strategies.arbitrage]
enabled = true
min_profit_threshold = "0.01"  # Minimum 0.01 ETH profit
max_trade_size = "10.0"        # Maximum 10 ETH trade size
max_price_impact = 0.05        # Maximum 5% price impact
supported_dexes = ["uniswap_v2", "sushiswap", "uniswap_v3"]

[strategies.sandwich]
enabled = true
min_target_value = "0.5"       # Minimum 0.5 ETH victim transaction
max_slippage = 0.03           # Maximum 3% slippage to cause
max_frontrun_size = "5.0"     # Maximum 5 ETH frontrun

[strategies.liquidation]
enabled = true
protocols = ["aave", "compound", "makerdao"]
min_health_factor = 1.05      # Liquidate below 1.05 health factor
max_liquidation_amount = "50.0"  # Maximum 50 ETH liquidation

[flashbots]
relay_url = "https://relay.flashbots.net"
builder_urls = [
    "https://relay.flashbots.net",
    "https://builder0x69.io",
    "https://rpc.beaverbuild.org"
]
max_priority_fee_per_gas = "2"  # 2 gwei
max_fee_per_gas = "50"          # 50 gwei
private_key = "your_private_key_here"

[safety]
max_concurrent_bundles = 5
max_daily_gas_spend = "1.0"     # 1 ETH per day
emergency_stop_loss = "0.1"     # Stop if lose 0.1 ETH
max_position_size = "10.0"      # Maximum 10 ETH position
enable_emergency_stop = true

[monitoring]
enable_discord_alerts = false
discord_webhook_url = ""
enable_telegram_alerts = false
telegram_bot_token = ""
telegram_chat_id = ""
profit_report_interval = "0 8 * * *"  # Daily at 8 AM
log_level = "info"
metrics_port = 9090

[performance]
max_concurrent_analysis = 10
batch_processing_interval = 100  # milliseconds
mempool_filter_min_value = "0.1"     # 0.1 ETH minimum
mempool_filter_min_gas_price = "10"  # 10 gwei minimum
enable_metrics = true
cache_size = 10000

# DEX Configurations
[[dexes]]
name = "uniswap_v2"
router = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
factory = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
fee = 300  # 0.3%
enabled = true

[[dexes]]
name = "sushiswap"
router = "0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F"
factory = "0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac"
fee = 300  # 0.3%
enabled = true

[[dexes]]
name = "uniswap_v3"
router = "0xE592427A0AEce92De3Edee1F18E0157C05861564"
factory = "0x1F98431c8aD98523631AE4a59f267346ea31F984"
fee = 500  # Variable fees
enabled = true

# Token Addresses
[tokens]
WETH = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
USDC = "0xA0b86a33E6417f8C681A1fFE6954e127c9cd8e46"
USDT = "0xdAC17F958D2ee523a2206206994597C13D831ec7"
DAI = "0x6B175474E89094C44Da98b954EedeAC495271d0F"
WBTC = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"